//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProductResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Category Name 的當地語系化字串。
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Category Name is Required 的當地語系化字串。
        /// </summary>
        internal static string CategoryName_Require_Message {
            get {
                return ResourceManager.GetString("CategoryName_Require_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a text format 的當地語系化字串。
        /// </summary>
        internal static string CatrgoryName_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("CatrgoryName_DataType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Date 的當地語系化字串。
        /// </summary>
        internal static string Create_Date {
            get {
                return ResourceManager.GetString("Create_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Date 的當地語系化字串。
        /// </summary>
        internal static string Delete_Date {
            get {
                return ResourceManager.GetString("Delete_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string Delete_Flag {
            get {
                return ResourceManager.GetString("Delete_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Updated 的當地語系化字串。
        /// </summary>
        internal static string Modify_Date {
            get {
                return ResourceManager.GetString("Modify_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Manual 的當地語系化字串。
        /// </summary>
        internal static string ProductExplain {
            get {
                return ResourceManager.GetString("ProductExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a text format 的當地語系化字串。
        /// </summary>
        internal static string ProductExplain_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductExplain_DataType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The maximum number of words is 4000 words 的當地語系化字串。
        /// </summary>
        internal static string ProductExplain_StringLength_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductExplain_StringLength_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product ID 的當地語系化字串。
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a text format 的當地語系化字串。
        /// </summary>
        internal static string ProductID_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductID_DataType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product ID is Required 的當地語系化字串。
        /// </summary>
        internal static string ProductID_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductID_Required_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product id must be greater than 2 characters and less than 15 characters 的當地語系化字串。
        /// </summary>
        internal static string ProductID_StringLength_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductID_StringLength_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Image 的當地語系化字串。
        /// </summary>
        internal static string ProductImg {
            get {
                return ResourceManager.GetString("ProductImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Image 的當地語系化字串。
        /// </summary>
        internal static string ProductImg_DB {
            get {
                return ResourceManager.GetString("ProductImg_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Name 的當地語系化字串。
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a text format 的當地語系化字串。
        /// </summary>
        internal static string ProductName_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductName_DataType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Name is Required 的當地語系化字串。
        /// </summary>
        internal static string ProductName_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductName_Required_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product name must be greater than 2 characters and less than 15 characters 的當地語系化字串。
        /// </summary>
        internal static string ProductName_StringLength_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductName_StringLength_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Price 的當地語系化字串。
        /// </summary>
        internal static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a number format 的當地語系化字串。
        /// </summary>
        internal static string ProductPrice_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductPrice_DataType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Price must be between 1-1000000 的當地語系化字串。
        /// </summary>
        internal static string ProductPrice_Range_ErrorMessage {
            get {
                return ResourceManager.GetString("ProductPrice_Range_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Price is Required 的當地語系化字串。
        /// </summary>
        internal static string ProductPrice_Required_Message {
            get {
                return ResourceManager.GetString("ProductPrice_Required_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shelf 的當地語系化字串。
        /// </summary>
        internal static string Shelf_Flag {
            get {
                return ResourceManager.GetString("Shelf_Flag", resourceCulture);
            }
        }
    }
}
