//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateProductResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateProductResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingCar.App_GlobalResources.CreateProductResource", typeof(CreateProductResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add a single product 的當地語系化字串。
        /// </summary>
        public static string Add_single_product {
            get {
                return ResourceManager.GetString("Add_single_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to import? 的當地語系化字串。
        /// </summary>
        public static string Confirm_import {
            get {
                return ResourceManager.GetString("Confirm_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create 的當地語系化字串。
        /// </summary>
        public static string Create_button {
            get {
                return ResourceManager.GetString("Create_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Product 的當地語系化字串。
        /// </summary>
        public static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data format 的當地語系化字串。
        /// </summary>
        public static string Data_format {
            get {
                return ResourceManager.GetString("Data_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1.ProductID must be greater than 2 characters and less than 15 characters 的當地語系化字串。
        /// </summary>
        public static string Data_format_1 {
            get {
                return ResourceManager.GetString("Data_format_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2.ProductName must be greater than 2 characters and less than 15 characters. 的當地語系化字串。
        /// </summary>
        public static string Data_format_2 {
            get {
                return ResourceManager.GetString("Data_format_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3.ProductExplain is up to 4000 words 的當地語系化字串。
        /// </summary>
        public static string Data_format_3 {
            get {
                return ResourceManager.GetString("Data_format_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 4.ProductPrice is between 1~1000000 的當地語系化字串。
        /// </summary>
        public static string Data_format_4 {
            get {
                return ResourceManager.GetString("Data_format_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 5.ProductImg format is only jpg, png, jpeg, jfif 的當地語系化字串。
        /// </summary>
        public static string Data_format_5 {
            get {
                return ResourceManager.GetString("Data_format_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Excel import Product 的當地語系化字串。
        /// </summary>
        public static string Excel_create_product {
            get {
                return ResourceManager.GetString("Excel_create_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add more than 1000 products through Excel 的當地語系化字串。
        /// </summary>
        public static string Excel_insert1000 {
            get {
                return ResourceManager.GetString("Excel_insert1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Import 的當地語系化字串。
        /// </summary>
        public static string Import_button {
            get {
                return ResourceManager.GetString("Import_button", resourceCulture);
            }
        }
    }
}
