//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;     

    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }

        public string OrderID { get; set; }

        [Display(Name ="會員ID")]
        public string UserID { get; set; }

        public string ProductID { get; set; }

        [Display(Name = "產品名稱")]
        public string ProductName { get; set; }

        [Display(Name = "數量")]
        public Nullable<int> ProductQty { get; set; }

        [Display(Name = "價錢")]
        public Nullable<decimal> TotalPrice { get; set; }

        [Display(Name = "下訂日期")]
        public Nullable<System.DateTime> Create_Date { get; set; }

        public Nullable<System.DateTime> Modify_Date { get; set; }

        public Nullable<System.DateTime> Delete_Date { get; set; }

        public Nullable<bool> Delete_Flag { get; set; }

        public bool Approved_Flag { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }

        public virtual Product Product { get; set; }
    }
}
